FROM node:20-slim

RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY package*.json ./
RUN npm install
RUN npm i -g tsx
COPY . .

ENV NODE_ENV=development
EXPOSE 8001

CMD ["npm", "run", "dev"]
